/**
 * fig-memo 厂商别名映射（自动生成）：标题里的写法 → hpoi 中文规范名。
 * 由人工核对 hpoi 公司页后生成，勿手改（见 node 端脚本）。
 */
export const FIGMEMO_MANUFACTURER_ALIAS: Record<string, string> = {
  '39': '39NASU',
  AD: 'Astrum Design',
  ADAMAS: 'ADAMAS金石',
  AMA: 'AMAKUNI',
  ANIPLEX: 'ANIPLEX+',
  'ANIPLX+': 'ANIPLEX+',
  ANS: 'ANIPLEX+',
  AO: 'Alpha × Omega',
  AP: 'A-PLUS',
  APEX: 'APEX-TOYS',
  AX: 'Alphamax',
  AliceGlint: 'Alice Glint',
  'Alter × Mega': 'Alpha × Omega',
  'Amor Fabrica': 'AmorFabrica',
  'AniGift×AniGame': 'AniGift',
  AniMester: '大漫匠AniMester',
  Animester: '大漫匠AniMester',
  AstrumDesign: 'Astrum Design',
  'A＋': 'A-PLUS',
  'B.R. Honey': 'B.R.Honey',
  'BANDAI SPIRITS CO.': 'BANDAI SPIRITS',
  BANPRESTO: '眼镜厂',
  BD: 'BINDing',
  BDS: 'BANDAI SPIRITS',
  BF: 'Bell Fine',
  BP: '眼镜厂',
  BS: 'BANDAI SPIRITS',
  'Bandai Co.': '万代',
  BeBOX: 'BEBOX',
  'Bear Panda': 'BearPanda',
  BellFine: 'Bell Fine',
  BibiButtons: 'Bibi Buttons',
  Bibi_Buttons: 'Bibi Buttons',
  'Brilliant Journey！': 'Brilliant Journey!',
  BrilliantJourney: 'Brilliant Journey!',
  'B´full': "B'full",
  'B´full FOTS JAPAN': 'FOTS JAPAN',
  'CLIP☆CRAFT': 'Clip☆Craft',
  DT: 'DRAGON Toy',
  'Deity’s Collector': 'Deitys Collector',
  DesignCOCO: 'Design COCO',
  'Doki max': 'DOKIMAX',
  EF: 'Eclipse Feather',
  EasyEight: 'E8',
  FANZA: 'FANesse',
  'FANesse by FANZA': 'FANesse',
  FunnyKnights: 'Funny Knights',
  GOLDENHEAD: '黄金頭GOLDEN HEAD',
  'GOLDENHEAD+': '黄金頭GOLDEN HEAD',
  GSAS: '良笑塑美',
  GSC: '良笑',
  GV: 'Gal.v',
  'Gal.V': 'Gal.v',
  'Girls&amp;Love': 'Gal.v',
  'Good Smile Arts': '良笑塑美',
  'Good Smile Company': '良笑',
  'HAKOIRI MUSUME Inc.': '箱娘',
  HJ: 'Hobby JAPAN',
  HM: 'HobbyMax',
  Hanabee: 'HanaBee',
  'Hobby Max': 'HobbyMax',
  'Hobby sakura': 'Hobby·sakura',
  KADOKAWA: 'KADOKAWA CREATORS',
  KADOKAWAクリエイターズ: 'KADOKAWA CREATORS',
  KAITENDOH: '回天堂',
  KAODKAWA: 'KADOKAWA CREATORS',
  'KING RECORD CO.': '国王唱片',
  'KOTOBUKIYA(コトブキヤ)': '寿屋',
  'Koei Tecmo Games': 'KT model+',
  'LEVEL MAX': 'Max Factory',
  'LTD.': 'BANDAI SPIRITS',
  'Lim Land/VKEND': 'Lim Land',
  'Lovely Project': 'Lovely',
  'Ltd.': '万代',
  'Luminous box': '光菱-LBOX',
  'MAX FACTORY': 'Max Factory',
  MF: 'Max Factory',
  MH: 'MegaHouse',
  MU: 'MouseUnit',
  MW: 'ModelWay',
  Max: 'Max Factory',
  MaxFactory: 'Max Factory',
  'Mega House': 'MegaHouse',
  'Model Way': 'ModelWay',
  NEKOYOME: 'Nekoyome',
  OMH: 'OMAHA',
  OT: 'ORCATOYS',
  OrientalForest: 'Oriental Forest',
  OtakuToys: 'Otaku Toys',
  PCMP: 'ポニーキャニオン音楽出版',
  'PINK MANGO': 'PINKMANGO',
  PL: 'PartyLook',
  PR: 'Pink Rouge',
  'Party Look': 'PartyLook',
  Partylook: 'PartyLook',
  'Pink Love': 'Pink love',
  PinkCharm: 'Pink Charm',
  PinkMango: 'PINKMANGO',
  'Pink・Cat': 'Pink Cat',
  'Pink・Charm': 'Pink Charm',
  'Pink・cat': 'Pink Cat',
  'Ponycanyon Music Publishing Inc.': 'ポニーキャニオン音楽出版',
  QT: 'QueenTed',
  REVOLVE: 'Claynel',
  Rencontre: 'RENCONTRE',
  'Reverse Studio': '逆转工作室',
  SAMELAP: 'Samelap',
  SE: '史克威尔艾尼克斯',
  SEGA: '世嘉',
  'SEGA Fave': '世嘉',
  'SHIBUYA SCRAMBLE FIGURE': 'SSF',
  SKY: 'SkyTube',
  'SKYTUBE PREMIUM': 'STP',
  SM: 'SPACE MOGURA',
  'SOUL WING': 'SOULWING精灵社',
  SQUAREENIX: '史克威尔艾尼克斯',
  'STP（スカイチューブプレミアム）': 'STP',
  Solarain: '青时雨',
  'Solarain Toys': '青时雨',
  S社: 'SkyTube',
  TBSグロウディア: 'TBS',
  TP: 'Tuberosa+',
  Taito: 'TAiTO',
  'Tokyo Otaku Mode': '东京宅',
  UC: 'UnionCreative',
  UMIKAWA: 'Umikawa',
  Uloop: 'U-loop',
  Unbound: 'UnBOUND',
  UnknownModel: '幽蓦文化',
  UnknownModel幽蓦文化: '幽蓦文化',
  Uya: '尤雅',
  'Violet Studio': 'VIOLET STUDIO',
  WW: 'Wonderful Works',
  'WithFans!': 'With Fans!',
  WonderfulWorks: 'Wonderful Works',
  alphamax: 'Alphamax',
  apextoys: 'APEX-TOYS',
  aplus: 'A-PLUS',
  'aq-marine': 'AQUAMARINE',
  'b&#39;full': 'Bfull',
  bd: '万代',
  'be-full': 'Bfull',
  'bed room honey studio': 'B.R.Honey',
  'bedroomhoney studio': 'B.R.Honey',
  bell_fine: 'Bell Fine',
  fnex: 'F:NEX',
  'hobby sakura': 'Hobby·sakura',
  hobbysakura: 'Hobby·sakura',
  hobbystock: 'HOBBY STOCK',
  knead: 'Knead',
  kneed: 'Knead',
  limland: 'Lim Land',
  magiarts: 'MAGI ARTS',
  'miHoYo/APEX': 'miHoYo',
  orchid_seed: 'Orchid Seed',
  orchidseed: 'Orchid Seed',
  ourtreasure: 'Our Treasure',
  qsix: 'Q-six',
  rocketboy: 'Rocket Boy',
  sikiAnim: 'SIKI ANIM',
  supernova: 'Super Nova',
  uloop: 'U-loop',
  wave: 'WAVE',
  '【限定販売】Q-six': 'Q-six',
  あみあみ: 'AmiAmi',
  'あみあみ 美少女フィギュア展示撮影': 'AmiAmi',
  あみあみZero: 'AmiAmi',
  'あみあみ×AMAKUINI': 'AmiAmi',
  'あみあみ×AMAKUNI': 'AMAKUNI',
  'あみあみ×AniGame': 'AniGame',
  'あみあみ×AniGift': 'AniGift',
  'あみあみ秋葉原フィギュアタワー店　展示撮影': 'AmiAmi',
  えいてぃーん: 'Eighteen',
  のくちゅるぬ: 'NOCTURNE',
  びーふる: 'Bfull',
  'びーふる フォトス ジャパン': 'Bfull FOTS JAPAN',
  わんだらー: '玩达乐',
  アイヴ: 'I.V.E',
  アクアマリン: 'AQUAMARINE',
  'アスキー・メディアワークス': 'メディアワークス',
  アニプレックス: 'Aniplex上海',
  アニプレックスプラス: 'ANIPLEX+',
  アニプレックス上海: 'Aniplex上海',
  アマクニ: 'AMAKUNI',
  アモールファブリカ: 'AmorFabrica',
  アリスグリント: 'Alice Glint',
  アルター: 'Alter',
  アルファオメガ: 'Alpha × Omega',
  アルファマックス: 'Alphamax',
  アルミナ: 'ALUMINA',
  アワートレジャー: 'Our Treasure',
  インサイト: 'Insight',
  イージーエイト: 'E8',
  ウイング: 'WING',
  ウェーブ: 'WAVE',
  エイプラス: 'A-PLUS',
  エレガント: 'ELEGANT',
  エンソウトイズ: 'ENSOUTOYS',
  'オリエンタル フォレスト': 'Oriental Forest',
  オルカトイズ: 'ORCATOYS',
  オーキッドシード: 'Orchid Seed',
  キャラアニ: 'chara-ani',
  キングレコード: '国王唱片',
  キングレコード株式会社: '国王唱片',
  クイーンテッド: 'QueenTed',
  クレイラドール: 'Cleyera Doll',
  クレーネル: 'Claynel',
  グッスマ系: 'Max Factory',
  グッドスマイルアーツ上海: '良笑塑美',
  グッドスマイルカンパニー: '良笑',
  'グッドスマイルカンパニ－': '良笑',
  'グッドスマイル・カンパニー': '良笑',
  グリズリーパンダ: 'Grizzly Panda',
  コトブキヤ: '寿屋',
  コーエーテクモゲームス: 'KT model+',
  'コーエーテクモゲームス/KT model+': 'KT model+',
  ゴールデンヘッド: '黄金頭GOLDEN HEAD',
  ジェンコ: 'GENCO',
  ジェントルメン: 'Gentlemen',
  スカイチューブ: 'SkyTube',
  スカイチューブプレミアム: 'SkyTube',
  'スクウェア・エニックス': '史克威尔艾尼克斯',
  ストロンガー: 'Stronger',
  スペースモグラ: 'SPACE MOGURA',
  セイムラップ: 'Samelap',
  セガ: '世嘉',
  ゼニックス: 'RENCONTRE',
  'ソル・インターナショナル': 'SOL INTERNATIONAL',
  タイトー: 'TAiTO',
  ダイキ工業: 'DAIKI工业',
  チューベローズプラス: 'Tuberosa+',
  'チューベローズプラス(オーキッドシード)': 'Tuberosa+',
  'ディ・モールト ベネ': 'Di molto bene',
  'ディ・モールトベネ': 'Di molto bene',
  デザインココ: 'Design COCO',
  ドラゴントイ: 'DRAGON Toy',
  'ドラゴン・トイ': 'DRAGON Toy',
  ネイティブ: 'Native',
  ネイティブグループ合同展示会: 'Native',
  ネイティブフィギュアのFANZA在庫状況: 'Native',
  ノクタナス: 'NOCTURNAS',
  バインディング: 'BINDing',
  バンダイ: '万代',
  バンダイスピリッツ: 'BANDAI SPIRITS',
  バンプレスト: '眼镜厂',
  ピンクキャット: 'Pink Cat',
  'ファット・カンパニー': 'Phat!',
  ファニーナイツ: 'Funny Knights',
  ファネス: 'FANesse',
  ファレノ: 'Phalaeno',
  フリュー: 'FuRyu',
  フリーイング: 'FREEing',
  フレア: 'FLARE',
  フロッグ: 'FROG',
  ブロッコリー: 'Broccoli',
  プラム: 'PLUM',
  プルクラ: 'PULCHRA',
  プレアデス: 'PLEIADES',
  ベルファイン: 'Bell Fine',
  ホビーサクラ: 'Hobby·sakura',
  ホビージャパン: 'Hobby JAPAN',
  ホビーストック: 'HOBBY STOCK',
  ホビーマックス: 'HobbyMax',
  ポニーキャニオン: 'ポニーキャニオン音楽出版',
  マウスユニット: 'MouseUnit',
  マックスファクトリー: 'Max Factory',
  ミメヨイ: 'Mimeyoi',
  ミューズモールド: 'MuseMolds',
  ミートス: 'Myethos',
  メガハウス: 'MegaHouse',
  メルヘンパンチ: 'Märchen Punch',
  ユニオンクリエイティブ: 'UnionCreative',
  'ユニオンクリエイティブインタ−ナショナル': 'UnionCreative',
  リコルヌ: 'Licorne',
  リボルブ: 'Claynel',
  リューノス: 'Ryu-NS',
  ルミナスボックス: '光菱-LBOX',
  レチェリー: 'Lechery',
  ロケットボーイ: 'Rocket Boy',
  ワンダフルワークス: 'Wonderful Works',
  'ワンフェス2018夏　ANIPLEX+': 'ANIPLEX+',
  'ワンフェス2018夏　KADOKAWA＆キャラアニ': 'chara-ani',
  'ワンフェス2018夏　Q-six': 'Q-six',
  'ワンフェス2018夏　アクアマリン': 'AQUAMARINE',
  'ワンフェス2018夏　アルター': 'Alter',
  'ワンフェス2018夏　アルファマックス': 'Alphamax',
  'ワンフェス2018夏　オーキッドシード（一般）': 'Orchid Seed',
  'ワンフェス2018夏　コトブキヤ': '寿屋',
  'ワンフェス2018夏　ジェンコ': 'GENCO',
  'ワンフェス2018夏　フリュー': 'FuRyu',
  'ワンフェス2018夏　フレア': 'FLARE',
  'ワンフェス2018夏　プラム': 'PLUM',
  'ワンフェス2018夏　ベルファイン': 'Bell Fine',
  'ワンフェス2018夏　ホビージャパン': 'Hobby JAPAN',
  'ワンフェス2018夏　メガハウス': 'MegaHouse',
  'ワンフェス2018夏　ユニオンクリエイティブ': 'UnionCreative',
  'ワンフェス2018夏　ヴェルテクス': 'VERTEX',
  'ワンフェス2018夏　回天堂＆レチェリー': '回天堂',
  'ワンフェス2018夏　絵夢トイズ': 'Emontoys',
  ヴェルテクス: 'VERTEX',
  万代: 'BANDAI SPIRITS',
  万代精神: 'BANDAI SPIRITS',
  万代魂: 'BANDAI SPIRITS',
  万代魂事业部: 'BANDAI SPIRITS',
  兰种社: 'Orchid Seed',
  再版狂魔: '寿屋',
  前身Mirror: 'Myethos',
  千値練: '千值练',
  千大爷: '千值练',
  双翼社: 'WINGS inc.',
  哈纳彼: 'HanaBee',
  壽屋: '寿屋',
  大气工业: 'DAIKI工业',
  大漫匠: '大漫匠AniMester',
  大漫匠アニメスター: '大漫匠AniMester',
  大网株式会社: 'AmiAmi',
  太东: 'TAiTO',
  宇宙鼹鼠: 'SPACE MOGURA',
  安尼普: 'ANIPLEX+',
  '安尼普（上海）文化艺术有限公司': 'Aniplex上海',
  小A: 'Alphamax',
  尤雅Uya: '尤雅',
  尼德: 'Knead',
  异色狂魔: 'Q-six',
  弥索: 'Myethos',
  恋恋: '恋恋koikoi',
  星闪工作室: 'Astrum Design',
  未来工场: '良笑',
  未来工場: '良笑',
  '株式会社BANDAI SPIRITS(バンダイスピリッツ)': 'BANDAI SPIRITS',
  株式会社Knead: 'Knead',
  株式会社TBSテレビ: 'TBS',
  株式会社えいてぃーん: 'Eighteen',
  株式会社ウイング: 'WING',
  株式会社サンキューナス: '39NASU',
  '株式会社ソル・インターナショナル': 'SOL INTERNATIONAL',
  株式会社デザインココ: 'Design COCO',
  株式会社バンダイ: '万代',
  株式会社ホビージャパン: 'Hobby JAPAN',
  株式会社ポニーキャニオン音楽出版: 'ポニーキャニオン音楽出版',
  株式会社リコルヌ: 'Licorne',
  水族馆: 'AQUAMARINE',
  水蓝宝石: 'AQUAMARINE',
  海蓝宝石: 'AQUAMARINE',
  滑稽骑士: 'Funny Knights',
  火箭男孩: 'Rocket Boy',
  熊猫社: 'Grizzly Panda',
  狗屋: '寿屋',
  画饼社: 'Orchid Seed',
  皇声唱片: '国王唱片',
  眼光社: 'Insight',
  破烂社: 'PLUM',
  '第10回 ネイティブグループ合同展示会': 'Native',
  '第11回 ネイティブグループ合同展示会': 'Native',
  '第12回 ネイティブグループ合同展示会': 'Native',
  '第13回 ネイティブグループ合同展示会': 'Native',
  '第3回ネイティブグループ合同展示会（エロホビ）に行ってきた！': 'Native',
  '第6回 ネイティブグループ合同展示会': 'Native',
  '第7回 ネイティブグループ合同展示会へ行ってきました': 'Native',
  '第8回 ネイティブグループ合同展示会': 'Native',
  '第9回 ネイティブグループ合同展示会': 'Native',
  箱入り娘: '箱娘',
  箱入娘: '箱娘',
  粉色芒果: 'PINKMANGO',
  精灵沙滩: 'ELF BEACH',
  精灵海滩: 'ELF BEACH',
  絵夢トイズ: 'Emontoys',
  绅士社: 'Gentlemen',
  联合创意: 'UnionCreative',
  聚会样: 'PartyLook',
  肥特: 'Phat!',
  自由社: 'FREEing',
  萝莉社: 'PLUM',
  蓝标万代: 'BANDAI SPIRITS',
  财团B: 'BANDAI SPIRITS',
  轮转社: 'Claynel',
  金石工业: 'ADAMAS金石',
  镜叔: 'Myethos',
  '阿尔法 麦克斯': 'Alphamax',
  阿弥阿弥: 'AmiAmi',
  阿玛库尼: 'AMAKUNI',
  顶点社: 'VERTEX',
  高级万代: 'BANDAI SPIRITS',
  黄金頭GOLDENHEADPLUS: '黄金頭GOLDEN HEAD',
  鼠标元件: 'MouseUnit',
  龙玩具: 'DRAGON Toy',
};
